document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="./src/providers.css"><link rel="stylesheet" href="./src/vultr.css"><link rel="stylesheet" href="./src/integration-state.css"><link rel="stylesheet" href="./src/navigation.css">');
const icons={grid:'▦',server:'▤',globe:'◎',shield:'◇',card:'▱',wrench:'⌁',report:'◫',settings:'⚙',search:'⌕',bell:'♢',check:'✓',warn:'!',down:'×',clock:'◷',arrow:'↗'};
const websites=[
 {name:'Elite Advisors',url:'eliteadvisors.co',status:'Operational',uptime:'99.99%',latency:184,ssl:87,region:'London, UK'},
 {name:'Client Portal',url:'portal.eliteadvisors.co',status:'Operational',uptime:'99.97%',latency:236,ssl:87,region:'London, UK'},
 {name:'Insights Hub',url:'insights.eliteadvisors.co',status:'Degraded',uptime:'98.71%',latency:684,ssl:42,region:'Frankfurt, DE'},
 {name:'Advisor Connect',url:'connect.eliteadvisors.co',status:'Operational',uptime:'99.94%',latency:211,ssl:116,region:'London, UK'}
];
const activity=[
 ['check','Health check completed','All 8 production servers passed','2 min ago'],
 ['warn','High latency detected','insights.eliteadvisors.co · 684ms','18 min ago'],
 ['check','Backup completed','ea-prod-db-01 · 42.6 GB','1 hr ago'],
 ['clock','Maintenance scheduled','Kernel update · 20 Jul, 02:00 UTC','3 hrs ago']
];
const renewals=[
 ['Anthropic API','Usage based','£287.40','12 Jul','1 day','urgent'],
 ['eliteadvisors.co','Hostinger','£24.99','03 Aug','23 days','soon'],
 ['BitNinja Security','Annual','£356.00','18 Aug','38 days','ok'],
 ['Mail­erSend','Professional','£39.00','01 Sep','52 days','ok']
];
const providers=[['Vultr','Cloud servers','https://cdn.simpleicons.org/vultr/007BFC',true],['Cloudflare','DNS & domains','https://cdn.simpleicons.org/cloudflare/F38020',false],['BitNinja','Server security','https://cdn.simpleicons.org/bitdefender/ED1C24',false],['Hostinger','Domain registrar','https://cdn.simpleicons.org/hostinger/673DE6',false],['Anthropic','Claude API','https://cdn.simpleicons.org/anthropic/181818',false],['OpenAI','Codex','https://cdn.simpleicons.org/openai/10A37F',false],['MailerSend','Pending approval','https://cdn.simpleicons.org/maildotru/168DE2',false],['Wasabi','Cloud storage','https://cdn.simpleicons.org/wasabi/01A0E4',false]];

function lineChart(){return `<svg viewBox="0 0 720 160" preserveAspectRatio="none" aria-label="Uptime trend"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#39d8ad" stop-opacity=".23"/><stop offset="1" stop-color="#39d8ad" stop-opacity="0"/></linearGradient></defs><path class="area" d="M0 98 C45 92 55 68 105 72 S170 95 220 55 S292 72 340 63 S400 94 450 60 S530 45 585 49 S650 28 720 38 L720 160 L0 160Z"/><path class="line" d="M0 98 C45 92 55 68 105 72 S170 95 220 55 S292 72 340 63 S400 94 450 60 S530 45 585 49 S650 28 720 38"/><g class="dots"><circle cx="220" cy="55" r="4"/><circle cx="585" cy="49" r="4"/><circle cx="720" cy="38" r="4"/></g></svg>`}
function render(){document.querySelector('#app').innerHTML=`
<aside><div class="brand"><div class="brandmark">EA</div><div><strong>ELITE</strong><small>ADVISORS</small></div></div><nav>${[['grid','Overview'],['server','Infrastructure'],['globe','Websites'],['shield','Security'],['card','Subscriptions'],['wrench','Maintenance'],['report','Reports']].map((x,i)=>`<button class="navitem ${i===0?'active':''}" data-view="${x[1]}"><span>${icons[x[0]]}</span>${x[1]}${x[1]==='Security'?'<i>2</i>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><button class="navitem"><span>${icons.settings}</span>Settings</button><div class="support"><span>IT</span><div><b>IT Operations</b><small>it@eliteadvisors.co</small></div><button>⋮</button></div></div></aside>
<main><header><div><p>OPERATIONS CENTER</p><h1>Good morning, IT Team</h1><span>Here’s the current state of your digital infrastructure.</span></div><div class="head-actions"><label>${icons.search}<input placeholder="Search anything..."><kbd>⌘ K</kbd></label><button class="iconbtn">${icons.bell}<i></i></button><button class="primary" id="runCheck">${icons.arrow} Run health check</button></div></header>
<section class="statusbar"><div><i></i><b>Vultr systems operational</b><span>1 of ${providers.length} providers connected</span></div><button>View integrations →</button></section>
<section class="providerbar" id="integrations"><div class="provider-title"><b>Service integrations</b><span>${providers.filter(p=>p[3]).length} connected · ${providers.length-1} pending</span></div>${providers.map(p=>`<div class="provider ${p[3]?'connected':'pending'}"><img src="${p[2]}" alt="${p[0]} logo"><div><b>${p[0]}</b><span>${p[3]?'Connected':p[1]}</span></div><i></i></div>`).join('')}</section>
<section class="stats">
${[['server','Vultr servers','—','Connecting…','positive'],['globe','Websites','0','Not connected','disabled'],['shield','Security','—','Not connected','disabled'],['card','Tracked spend','£0.00','No billing sources','disabled']].map(x=>`<article class="stat ${x[4]==='disabled'?'stat-disabled':''}"><div class="stat-icon ${x[4]}">${icons[x[0]]}</div><div><span>${x[1]}</span><strong>${x[2]}</strong><small class="${x[4]}">${x[3]}</small></div><button>↗</button></article>`).join('')}</section>
<section class="card vultr-live" id="infrastructure"><div class="cardhead"><div><h2><img src="https://cdn.simpleicons.org/vultr/007BFC" alt="Vultr logo"> Vultr infrastructure</h2><p>Live server inventory · refreshed every 5 minutes</p></div><span id="vultrUpdated">Connecting…</span></div><div id="vultrServers" class="server-grid"><p>Loading server status…</p></div></section>
<section class="dashboard-grid"><article class="card performance"><div class="cardhead"><div><h2>System performance</h2><p>Average uptime across all services</p></div><select><option>Last 7 days</option><option>Last 30 days</option></select></div><div class="uptime"><strong>99.94%</strong><span>↑ 0.12%</span><small>vs previous period</small></div><div class="chart">${lineChart()}<div class="axis"><span>Fri 05</span><span>Sat 06</span><span>Sun 07</span><span>Mon 08</span><span>Tue 09</span><span>Wed 10</span><span>Today</span></div></div></article>
<article class="card activity"><div class="cardhead"><div><h2>Recent activity</h2><p>Live updates from your systems</p></div><button>View all</button></div><div class="activity-list">${activity.map(a=>`<div class="activity-row"><span class="event ${a[0]}">${icons[a[0]]}</span><div><b>${a[1]}</b><p>${a[2]}</p></div><time>${a[3]}</time></div>`).join('')}</div></article></section>
<section class="card sites disconnected-panel" id="websites"><div class="cardhead"><div><h2>Website health</h2><p>Availability, latency and SSL monitoring</p></div><button>Pending setup</button></div><div class="empty-state"><span>${icons.globe}</span><div><b>Website monitoring is not connected yet</b><p>Cloudflare and website endpoints will be configured in a later integration step.</p></div></div></section>
<section class="pending-modules"><article class="card disconnected-panel" id="security"><div class="cardhead"><div><h2>Security monitoring</h2><p>BitNinja incidents, threats and security posture</p></div><button>Pending BitNinja</button></div><div class="empty-state"><span>${icons.shield}</span><div><b>Security data is not connected yet</b><p>BitNinja will provide live threat and incident information.</p></div></div></article><article class="card disconnected-panel" id="subscriptions"><div class="cardhead"><div><h2>Subscriptions and costs</h2><p>Plans, usage, renewals and expiry dates</p></div><button>Pending providers</button></div><div class="empty-state"><span>${icons.card}</span><div><b>Billing sources are not connected yet</b><p>Costs will appear as each subscription provider is onboarded.</p></div></div></article></section>
<section class="lower-grid"><article class="card renewals"><div class="cardhead"><div><h2>Upcoming renewals</h2><p>Subscriptions and services requiring attention</p></div><button>View all →</button></div>${renewals.map(r=>`<div class="renewal"><span class="vendor">${r[0].slice(0,2).toUpperCase()}</span><div><b>${r[0]}</b><small>${r[1]}</small></div><strong>${r[2]}</strong><div class="date"><b>${r[3]}</b><small class="${r[5]}">${r[4]}</small></div></div>`)}</article><article class="card risks"><div class="cardhead"><div><h2>Risk register</h2><p>Open issues requiring action</p></div><button>View register →</button></div><div class="risk high"><em>HIGH</em><div><b>API subscription renews tomorrow</b><p>Anthropic billing method requires verification.</p></div><span>Owner<br><b>IT Admin</b></span></div><div class="risk medium"><em>MEDIUM</em><div><b>Insights Hub performance</b><p>Response time exceeded 500ms threshold.</p></div><span>Owner<br><b>DevOps</b></span></div><div class="risk low"><em>LOW</em><div><b>Server OS update available</b><p>Security patches ready for 3 instances.</p></div><span>Owner<br><b>IT Team</b></span></div></article></section>
<footer>Elite Advisors IT Operations Console <span>•</span> All times shown in UTC <b>Console v1.0</b></footer></main><div id="toast"></div>`;
bind();}
function bind(){const targets={Overview:'app',Infrastructure:'infrastructure',Websites:'websites',Security:'security',Subscriptions:'subscriptions',Maintenance:'integrations',Reports:'integrations'},messages={Infrastructure:'Showing live Vultr infrastructure',Websites:'Website monitoring is pending connection',Security:'BitNinja security monitoring is pending connection',Subscriptions:'Subscription providers are pending connection',Maintenance:'Maintenance planning will follow the core integrations',Reports:'Reports will use data from connected providers'};document.querySelectorAll('.navitem[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navitem').forEach(x=>x.classList.remove('active'));b.classList.add('active');let target=document.getElementById(targets[b.dataset.view]);if(target)target.scrollIntoView({behavior:'smooth',block:'start'});if(messages[b.dataset.view])showToast(messages[b.dataset.view])});document.querySelector('#runCheck').onclick=e=>{let b=e.currentTarget;b.disabled=true;b.textContent='◷ Running Vultr check...';setTimeout(()=>{b.disabled=false;b.textContent='↗ Run health check';document.querySelector('.statusbar span').textContent='1 of 8 providers connected';showToast('Vultr status refreshed · 3 servers operational')},1800)};document.querySelector('header input').addEventListener('input',e=>{let q=e.target.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')})}
function loadVultr(){fetch('./data/vultr.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{let st=document.querySelector('.stats .stat:first-child');st.querySelector('strong').textContent=`${d.operational} / ${d.count}`;st.querySelector('small').textContent=d.operational===d.count?'All operational':`${d.count-d.operational} require attention`;document.querySelector('#vultrUpdated').textContent=`Updated ${new Date(d.generated_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;document.querySelector('#vultrServers').innerHTML=d.instances.map(s=>`<article><div class="server-top"><span class="server-logo">V</span><div><b>${s.label||s.hostname}</b><small>${s.region} · ${s.os}</small></div><em class="${s.status==='active'&&s.power_status==='running'?'online':'offline'}"><i></i>${s.power_status||s.status}</em></div><div class="server-specs"><span><b>${s.vcpu_count}</b> vCPU</span><span><b>${s.ram}</b> MB RAM</span><span><b>${s.disk}</b> GB disk</span><span><b>${s.server_status||'—'}</b> health</span></div></article>`).join('')}).catch(()=>{document.querySelector('#vultrUpdated').textContent='Connection unavailable';document.querySelector('#vultrServers').innerHTML='<p>Live Vultr data is temporarily unavailable.</p>'})}
function showToast(s){let t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}render();loadVultr();
