import './styles.css';

const icons={grid:'▦',server:'▤',globe:'◎',shield:'◇',card:'▱',wrench:'⌁',report:'◫',settings:'⚙',search:'⌕',bell:'♢',check:'✓',warn:'!',down:'×',clock:'◷',arrow:'↗'};
const websites=[
 {name:'Elite Advisors',url:'eliteadvisors.co',status:'Operational',uptime:'99.99%',latency:184,ssl:87,region:'London, UK'},
 {name:'Client Portal',url:'portal.eliteadvisors.co',status:'Operational',uptime:'99.97%',latency:236,ssl:87,region:'London, UK'},
 {name:'Insights Hub',url:'insights.eliteadvisors.co',status:'Degraded',uptime:'98.71%',latency:684,ssl:42,region:'Frankfurt, DE'},
 {name:'Advisor Connect',url:'connect.eliteadvisors.co',status:'Operational',uptime:'99.94%',latency:211,ssl:116,region:'London, UK'}
];
const activity=[
 ['check','Health check completed','All 8 production servers passed','2 min ago'],
 ['warn','High latency detected','insights.eliteadvisors.co · 684ms','18 min ago'],
 ['check','Backup completed','ea-prod-db-01 · 42.6 GB','1 hr ago'],
 ['clock','Maintenance scheduled','Kernel update · 20 Jul, 02:00 UTC','3 hrs ago']
];
const renewals=[
 ['Anthropic API','Usage based','£287.40','12 Jul','1 day','urgent'],
 ['eliteadvisors.co','Hostinger','£24.99','03 Aug','23 days','soon'],
 ['BitNinja Security','Annual','£356.00','18 Aug','38 days','ok'],
 ['Mail­erSend','Professional','£39.00','01 Sep','52 days','ok']
];

function lineChart(){return `<svg viewBox="0 0 720 160" preserveAspectRatio="none" aria-label="Uptime trend"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#39d8ad" stop-opacity=".23"/><stop offset="1" stop-color="#39d8ad" stop-opacity="0"/></linearGradient></defs><path class="area" d="M0 98 C45 92 55 68 105 72 S170 95 220 55 S292 72 340 63 S400 94 450 60 S530 45 585 49 S650 28 720 38 L720 160 L0 160Z"/><path class="line" d="M0 98 C45 92 55 68 105 72 S170 95 220 55 S292 72 340 63 S400 94 450 60 S530 45 585 49 S650 28 720 38"/><g class="dots"><circle cx="220" cy="55" r="4"/><circle cx="585" cy="49" r="4"/><circle cx="720" cy="38" r="4"/></g></svg>`}
function render(){document.querySelector('#app').innerHTML=`
<aside><div class="brand"><div class="brandmark">EA</div><div><strong>ELITE</strong><small>ADVISORS</small></div></div><nav>${[['grid','Overview'],['server','Infrastructure'],['globe','Websites'],['shield','Security'],['card','Subscriptions'],['wrench','Maintenance'],['report','Reports']].map((x,i)=>`<button class="navitem ${i===0?'active':''}" data-view="${x[1]}"><span>${icons[x[0]]}</span>${x[1]}${x[1]==='Security'?'<i>2</i>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><button class="navitem"><span>${icons.settings}</span>Settings</button><div class="support"><span>IT</span><div><b>IT Operations</b><small>it@eliteadvisors.co</small></div><button>⋮</button></div></div></aside>
<main><header><div><p>OPERATIONS CENTER</p><h1>Good morning, IT Team</h1><span>Here’s the current state of your digital infrastructure.</span></div><div class="head-actions"><label>${icons.search}<input placeholder="Search anything..."><kbd>⌘ K</kbd></label><button class="iconbtn">${icons.bell}<i></i></button><button class="primary" id="runCheck">${icons.arrow} Run health check</button></div></header>
<section class="statusbar"><div><i></i><b>All core systems operational</b><span>Last checked 2 minutes ago</span></div><button>View system status →</button></section>
<section class="stats">
${[['server','Servers','8 / 8','Operational','positive'],['globe','Websites','3 / 4','1 degraded','warning'],['shield','Security','96','Security score','positive'],['card','Monthly spend','£842.39','+4.2% this month','neutral']].map(x=>`<article class="stat"><div class="stat-icon ${x[4]}">${icons[x[0]]}</div><div><span>${x[1]}</span><strong>${x[2]}</strong><small class="${x[4]}">${x[3]}</small></div><button>↗</button></article>`).join('')}</section>
<section class="dashboard-grid"><article class="card performance"><div class="cardhead"><div><h2>System performance</h2><p>Average uptime across all services</p></div><select><option>Last 7 days</option><option>Last 30 days</option></select></div><div class="uptime"><strong>99.94%</strong><span>↑ 0.12%</span><small>vs previous period</small></div><div class="chart">${lineChart()}<div class="axis"><span>Fri 05</span><span>Sat 06</span><span>Sun 07</span><span>Mon 08</span><span>Tue 09</span><span>Wed 10</span><span>Today</span></div></div></article>
<article class="card activity"><div class="cardhead"><div><h2>Recent activity</h2><p>Live updates from your systems</p></div><button>View all</button></div><div class="activity-list">${activity.map(a=>`<div class="activity-row"><span class="event ${a[0]}">${icons[a[0]]}</span><div><b>${a[1]}</b><p>${a[2]}</p></div><time>${a[3]}</time></div>`).join('')}</div></article></section>
<section class="card sites"><div class="cardhead"><div><h2>Website health</h2><p>Live availability, response time and SSL status</p></div><button>Manage websites →</button></div><table><thead><tr><th>Website</th><th>Status</th><th>Uptime (30d)</th><th>Response</th><th>SSL expires</th><th>Region</th><th></th></tr></thead><tbody>${websites.map(w=>`<tr><td><span class="site-icon">${icons.globe}</span><div><b>${w.name}</b><small>${w.url}</small></div></td><td><em class="pill ${w.status==='Degraded'?'amber':'green'}"><i></i>${w.status}</em></td><td><b>${w.uptime}</b></td><td><span class="latency ${w.latency>500?'slow':''}">${w.latency} ms</span></td><td>${w.ssl} days</td><td>${w.region}</td><td>•••</td></tr>`).join('')}</tbody></table></section>
<section class="lower-grid"><article class="card renewals"><div class="cardhead"><div><h2>Upcoming renewals</h2><p>Subscriptions and services requiring attention</p></div><button>View all →</button></div>${renewals.map(r=>`<div class="renewal"><span class="vendor">${r[0].slice(0,2).toUpperCase()}</span><div><b>${r[0]}</b><small>${r[1]}</small></div><strong>${r[2]}</strong><div class="date"><b>${r[3]}</b><small class="${r[5]}">${r[4]}</small></div></div>`)}</article><article class="card risks"><div class="cardhead"><div><h2>Risk register</h2><p>Open issues requiring action</p></div><button>View register →</button></div><div class="risk high"><em>HIGH</em><div><b>API subscription renews tomorrow</b><p>Anthropic billing method requires verification.</p></div><span>Owner<br><b>IT Admin</b></span></div><div class="risk medium"><em>MEDIUM</em><div><b>Insights Hub performance</b><p>Response time exceeded 500ms threshold.</p></div><span>Owner<br><b>DevOps</b></span></div><div class="risk low"><em>LOW</em><div><b>Server OS update available</b><p>Security patches ready for 3 instances.</p></div><span>Owner<br><b>IT Team</b></span></div></article></section>
<footer>Elite Advisors IT Operations Console <span>•</span> All times shown in UTC <b>Console v1.0</b></footer></main><div id="toast"></div>`;
bind();}
function bind(){document.querySelectorAll('.navitem[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navitem').forEach(x=>x.classList.remove('active'));b.classList.add('active');showToast(`${b.dataset.view} module selected — connect live data to enable this view.`)});document.querySelector('#runCheck').onclick=e=>{let b=e.currentTarget;b.disabled=true;b.textContent='◷ Running checks...';setTimeout(()=>{b.disabled=false;b.textContent='↗ Run health check';document.querySelector('.statusbar span').textContent='Last checked just now';showToast('Health check complete · 8 servers and 4 websites tested')},1800)};document.querySelector('header input').addEventListener('input',e=>{let q=e.target.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')})}
function showToast(s){let t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}render();
